// Package openapi Code generated by swaggo/swag. DO NOT EDIT
package openapi

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/captcha/email": {
            "get": {
                "description": "向指定邮箱发送验证码。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "captcha"
                ],
                "summary": "发送邮箱验证码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "邮箱",
                        "name": "email",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    }
                }
            }
        },
        "/api/captcha/email/verify": {
            "post": {
                "description": "校验邮箱验证码，成功后返回重置密码凭证。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "captcha"
                ],
                "summary": "校验邮箱验证码",
                "parameters": [
                    {
                        "description": "邮箱验证码参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.EmailCaptchaRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    }
                }
            }
        },
        "/api/paper/all": {
            "get": {
                "description": "返回全部试卷列表。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "paper"
                ],
                "summary": "获取全部试卷",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    }
                }
            }
        },
        "/api/paper/getPaperandRatingWithQuerys": {
            "post": {
                "description": "按试卷类型和年份分页查询试卷，同时返回评分和题目数量。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "paper"
                ],
                "summary": "分页查询试卷和评分",
                "parameters": [
                    {
                        "description": "查询条件",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.PaperQueryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    }
                }
            }
        },
        "/api/paper/getPaperwithQuerys": {
            "post": {
                "description": "按试卷类型和年份分页查询试卷。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "paper"
                ],
                "summary": "分页查询试卷",
                "parameters": [
                    {
                        "description": "查询条件",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.PaperQueryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    }
                }
            }
        },
        "/api/paper/intro": {
            "get": {
                "description": "根据试卷 ID 返回试卷简介、分区数量和各分区题目数量。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "paper"
                ],
                "summary": "获取试卷简介",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "试卷 ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    }
                }
            }
        },
        "/api/paper/type": {
            "get": {
                "description": "根据试卷类型查询试卷列表。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "paper"
                ],
                "summary": "按类型查询试卷",
                "parameters": [
                    {
                        "type": "string",
                        "description": "试卷类型，如 CET-4/CET-6",
                        "name": "type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    }
                }
            }
        },
        "/api/paper/types": {
            "get": {
                "description": "返回数据库中存在的全部试卷类型。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "paper"
                ],
                "summary": "获取全部试卷类型",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    }
                }
            }
        },
        "/api/question/getAllByIdSplitByPart": {
            "get": {
                "description": "返回指定试卷题目，并按 partName 分组。Part II 内按 questionOrder 排序。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "question"
                ],
                "summary": "按 Part 分组获取题目",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "试卷 ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    }
                }
            }
        },
        "/api/question/getAnswersByPaperId": {
            "get": {
                "description": "返回指定试卷的全部答案，并按答案序号排序。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "question"
                ],
                "summary": "获取试卷答案",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "试卷 ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    }
                }
            }
        },
        "/api/question/getById": {
            "get": {
                "description": "返回指定试卷下的全部题目。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "question"
                ],
                "summary": "按试卷 ID 获取题目",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "试卷 ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    }
                }
            }
        },
        "/api/question/getByType": {
            "get": {
                "description": "返回指定试卷下指定题型的题目。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "question"
                ],
                "summary": "按试卷 ID 和题型获取题目",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "试卷 ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "题型",
                        "name": "type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    }
                }
            }
        },
        "/api/user/info": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "根据 token 获取当前登录用户信息。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "获取当前用户信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    }
                }
            }
        },
        "/api/user/login": {
            "post": {
                "description": "使用用户名或邮箱登录，成功后返回 sa-token-go token。兼容旧 AES 密码，成功后升级为 bcrypt。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    }
                }
            }
        },
        "/api/user/logout": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "使当前 token 失效。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "用户登出",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    }
                }
            }
        },
        "/api/user/register": {
            "post": {
                "description": "使用用户名、密码、邮箱和邮箱验证码注册用户。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "注册参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    }
                }
            }
        },
        "/api/user/resetpassword": {
            "post": {
                "description": "使用邮箱和重置凭证重置密码。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "重置密码",
                "parameters": [
                    {
                        "description": "重置密码参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ResetPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "返回服务状态和数据库是否启用。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "健康检查",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.EmailCaptchaRequest": {
            "type": "object",
            "required": [
                "code",
                "email"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                }
            }
        },
        "dto.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "usernameorEmail"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "recaptchaToken": {
                    "type": "string"
                },
                "usernameorEmail": {
                    "type": "string"
                }
            }
        },
        "dto.PaperQueryRequest": {
            "type": "object",
            "required": [
                "page",
                "size"
            ],
            "properties": {
                "page": {
                    "type": "integer",
                    "minimum": 1
                },
                "size": {
                    "type": "integer",
                    "maximum": 100,
                    "minimum": 1
                },
                "type": {
                    "type": "string"
                },
                "year": {
                    "type": "integer"
                }
            }
        },
        "dto.RegisterRequest": {
            "type": "object",
            "required": [
                "captchacode",
                "email",
                "password",
                "username"
            ],
            "properties": {
                "captchacode": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "recaptchaToken": {
                    "type": "string"
                },
                "username": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 3
                },
                "usertype": {
                    "type": "integer"
                }
            }
        },
        "dto.ResetPasswordRequest": {
            "type": "object",
            "required": [
                "email",
                "password",
                "resetToken"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "resetToken": {
                    "type": "string"
                }
            }
        },
        "response.Body": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Onepractice API",
	Description:      "Onepractice 在线英语真题平台 Go 后端 API。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
