CREATE TABLE IF NOT EXISTS `exam_records` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `record_id` char(32) NOT NULL,
  `user_id` bigint NOT NULL,
  `paper_id` int NOT NULL DEFAULT 0,
  `paper_type` varchar(32) NOT NULL DEFAULT '',
  `paper_name` varchar(255) NOT NULL DEFAULT '',
  `exam_type` varchar(32) NOT NULL DEFAULT '',
  `is_finished` tinyint NOT NULL DEFAULT 0,
  `answers` mediumtext,
  `score` int NOT NULL DEFAULT 0,
  `total_score` int NOT NULL DEFAULT 0,
  `time_spend` int NOT NULL DEFAULT 0,
  `has_spend_time` bigint NOT NULL DEFAULT 0,
  `submit_ts` bigint NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_exam_records_record_id` (`record_id`),
  KEY `idx_exam_records_user_time` (`user_id`, `submit_ts`),
  KEY `idx_exam_records_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `essay_grading_results` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `task_id` char(32) NOT NULL,
  `user_id` bigint NOT NULL,
  `record_id` char(32) NOT NULL DEFAULT '',
  `title` text NOT NULL,
  `full_score` int NOT NULL DEFAULT 0,
  `total_score` decimal(6,2) NOT NULL DEFAULT 0,
  `grammar_score` decimal(6,2) NOT NULL DEFAULT 0,
  `topic_score` decimal(6,2) NOT NULL DEFAULT 0,
  `word_score` decimal(6,2) NOT NULL DEFAULT 0,
  `structure_score` decimal(6,2) NOT NULL DEFAULT 0,
  `word_num` int NOT NULL DEFAULT 0,
  `raw_result` json,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_egr_task_id` (`task_id`),
  KEY `idx_egr_record` (`record_id`),
  KEY `idx_egr_user_created` (`user_id`, `created_at`),
  KEY `idx_essay_grading_results_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
